# Environment and agent
ENV_ID: 'LunarLander-v2'
ENV_SEED: 0
AGENT: 'sarsa'

# Data locations
# NOTE: setting RECORD_DIR to an existing directory will overwrite!
# NOTE: CHECKPOINT_DIR can be anything when CONTINUE is False
RECORD_DIR: 'record/sarsa/'
CHECKPOINT_DIR: ''

# Run config
EPISODES: 8000
SAVE_EVERY: 100
STATE_BINS: [5, 5, 5, 5, 5, 5, 2, 2]  # per state dimension

STATE_BOUNDS: [[-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0],
               [-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0]]  # per state dimension
# for showing on the screen
VERBOSE: 1  # 0: nothing, 1: plots and saved videos, 2: every episode
CONTINUE: False

E_GREEDY: [1.0, 0.05, 1e5, 0.99] #alpha_start, alpha_end, alpha_steps, alpha_decay

# in this case, do only exponential decay
LEARNING_RATE: [0.2, 0.2, 0, 1] #epsilon_start, epsilon_end, epsilon_steps, epsilon_decay

DISCOUNT_RATE: 0.97 #gamma
